version: "3.1"
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: ${PGPASSWORD}
      POSTGRES_DB: ${PGDATABASE}
    expose:
      - "${PGPORT}"
    ports:
      - '${PGPORT}:${PGPORT}'
    command: -p ${PGPORT}
    volumes:
        - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  api:
    build: 
      dockerfile: Dockerfile.dev
      context: .
    ports:
      - ${PORT}:${PORT}
    volumes:
      - ./:/usr/app
    environment:
      - PORT=${PORT}
      - PGUSER=${PGUSER}
      - PGHOST=db
      - PGPASSWORD=${PGPASSWORD}
      - PGDATABASE=${PGDATABASE}
      - PGPORT=${PGPORT}
      - SECRET=${SECRET}
      - CON_STRING=${CON_STRING}